#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

# Stop on error
set -euo pipefail

python3 -m pip install --upgrade pip
python3 -m pip install setuptools wheel pbr
python3 -m pip install pyyaml
