#!/bin/bash

if [ $DIB_DEV_IMAGE != "loopvm" ]; then
    exit 0
fi

DPDK=dpdk-18.02
DPDK_UNTAR=dpdk-18.02

# pick up the kernel version for the target image
kernel_version=`ls -t /lib/modules | awk 'NR==1 {print}'`

mkdir dpdk
wget http://fast.dpdk.org/rel/$DPDK.tar.xz
tar xfJ $DPDK.tar.xz
cd $DPDK_UNTAR

export RTE_KERNELDIR=/lib/modules/$kernel_version/build
export ARCH=x86
make -j4 install T=x86_64-native-linuxapp-gcc

cp x86_64-native-linuxapp-gcc/app/testpmd ../dpdk
cp x86_64-native-linuxapp-gcc/kmod/igb_uio.ko ../dpdk
echo "set promisc all off" > /dpdk/testpmd_cmd.txt

cd ..
rm -f $DPDK.tar.xz
rm -rf $DPDK_UNTAR
