#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

# Stop on error
set -euo pipefail

# set accurate rc.local file corresponding to current image built
if [ $DIB_DEV_IMAGE = "loopvm" ]; then
    mv /etc/rc.d/rc.local.loopvm /etc/rc.d/rc.local
else
    mv /etc/rc.d/rc.local.generator /etc/rc.d/rc.local
fi
