#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

# Stop on error
set -euo pipefail

chmod +x /etc/rc.d/rc.local
chmod +x /etc/sysconfig/network-scripts/ifcfg-eth0
chmod +x /etc/profile.d/nfvbench.sh
chmod +x /nfvbench/configure-nfvbench.sh
chmod +x /nfvbench/start-nfvbench.sh
