#!/bin/bash

if [ $DIB_DEV_IMAGE != "generator" ]; then
    exit 0
fi

# TRex installation
mkdir -p /opt/trex
mkdir /var/log/nfvbench

wget --no-cache --no-check-certificate https://trex-tgn.cisco.com/trex/release/$TREX_VER.tar.gz
tar xzf $TREX_VER.tar.gz -C /opt/trex
rm -f /$TREX_VER.tar.gz
rm -f /opt/trex/$TREX_VER/trex_client_$TREX_VER.tar.gz
cp -a /opt/trex/$TREX_VER/automation/trex_control_plane/interactive/trex /usr/local/lib/python3.6/site-packages/
rm -rf /opt/trex/$TREX_VER/automation/trex_control_plane/interactive/trex

# NFVbench installation
cd /opt
git clone https://gerrit.opnfv.org/gerrit/nfvbench
cd nfvbench/
pip3 install . --use-deprecated=legacy-resolver
cp xtesting/testcases.yaml /usr/local/lib/python3.6/site-packages/xtesting/ci/testcases.yaml
python3 ./docker/cleanup_generators.py
rm -rf /opt/nfvbench/.git
# persist env variables
echo "export TREX_VER=\"$TREX_VER\"" >> /etc/profile.d/nfvbench.sh
echo "export TREX_EXT_LIBS=\"/opt/trex/$TREX_VER/external_libs\"" >> /etc/profile.d/nfvbench.sh
