#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

# Stop on error
set -euo pipefail

# Set UseDNS no value in sshd_config to reduce time to connect
echo "UseDNS no" >> /etc/ssh/sshd_config
