# docker file for creating a container that has nfvbench installed and ready to use

FROM centos:7

ENV TREX_VER="v2.79" \
    VM_IMAGE_VER="0.12" \
    PYTHONIOENCODING="utf8"

# Note: do not clone with --depth 1 as it will cause pbr to fail extracting the nfvbench version
# from the git tag

RUN yum update -y \
 && yum install -y \
      git \
      kmod \
      pciutils \
      python36 \
      gcc \
      nano \
      wget \
      net-tools \
      epel-release \
      python36-devel \
      iproute \
      elfutils-libelf-devel \
      patch \
 && ln -sf /usr/bin/python3.6 /usr/local/bin/python3 \
 && mkdir -p /opt/trex \
 && wget --no-cache --no-check-certificate \
      https://trex-tgn.cisco.com/trex/release/$TREX_VER.tar.gz -P /tmp \
 && tar xzf /tmp/$TREX_VER.tar.gz -C /opt/trex \
 && rm -f /tmp/$TREX_VER.tar.gz \
 && cp -a /opt/trex/$TREX_VER/automation/trex_control_plane/interactive/trex \
      /usr/lib/python3.6/site-packages/ \
 && rm -rf /opt/trex/$TREX_VER/automation/trex_control_plane/interactive/trex \
 && rm -f /opt/trex/$TREX_VER/trex_client_$TREX_VER.tar.gz \
 && wget https://bootstrap.pypa.io/get-pip.py -P /tmp \
 && python3 /tmp/get-pip.py pip==20.2.4 \
 && rm -f /tmp/get-pip.py \
 && pip3 install -U \
      pbr \
      setuptools \
 && cd / && git clone https://gerrit.opnfv.org/gerrit/nfvbench \
 && pip3 install -e /nfvbench \
 && rm -rf /nfvbench/.git \
 && wget -O /nfvbench/nfvbenchvm-$VM_IMAGE_VER.qcow2 \
      http://artifacts.opnfv.org/nfvbench/images/nfvbenchvm_centos-$VM_IMAGE_VER.qcow2 \
 # Override Xtesting testcases.yaml file by NFVbench default one
 && cp /nfvbench/xtesting/testcases.yaml \
      /usr/local/lib/python3.6/dist-packages/xtesting/ci/testcases.yaml \
 && python3 /nfvbench/docker/cleanup_generators.py \
 && yum remove -y \
      wget \
      git \
      gcc \
 && yum clean all -y \
 && mkdir -p /var/log/nfvbench

ENV TREX_EXT_LIBS "/opt/trex/$TREX_VER/external_libs"

ENTRYPOINT ["/nfvbench/docker/nfvbench-entrypoint.sh"]
